app = "hoopbrain-proxy"
primary_region = "ams"

kill_signal = "SIGINT"
kill_timeout = "5s"

[deploy]
  strategy = "immediate"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  
  # 🔥 Makineyi ASLA durdurmasın (özellikle free Plan için şart)
  auto_start_machines = true
  auto_stop_machines = false
  
  # 🔥 En az 1 makine her zaman çalışsın
  min_machines_running = 1

  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb" 
