name = "hoopbrain-proxy"
main = "worker.js"
compatibility_date = "2025-01-01"

account_id = "e1314ca11d75591a8d7d262a8bbecf33"
workers_dev = true

routes = [
    { pattern = "hoopbrain.xyz/*", zone_id = "0bdf3bd68420f8f8b0c062ae38592bcd" }
]

usage_model = "unbound"
compatibility_flags = []
